backend:
  name: git-gateway
  branch: main
media_folder: "images/akce"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "akce"
    label: "Akce"
    folder: "akceMD"
    create: true
    slug: "{{SouborRok}}{{SouborMesic}}{{SouborDen}}_{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/akce.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "akceMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum akce odkdy dokdy", name: "kdy", widget: "string"}
      - {label: "Název souboru rok", name: "SouborRok", widget: "string", default: "2023"}
      - {label: "Název souboru měsíc", name: "SouborMesic", widget: "string"}
      - {label: "Název souboru den", name: "SouborDen", widget: "string"}
      - {label: "Název souboru rok - konec - volitelný", name: "SouborRokKonec", widget: "string", default: "2023", required: false}
      - {label: "Název souboru měsíc - konec - volitelný", name: "SouborMesicKonec", widget: "string", required: false}
      - {label: "Název souboru den - konec - volitelný", name: "SouborDenKonec", widget: "string", required: false}
      - {label: "Misto konani akce", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Stránky registrace - není povinné vyplnit", name: "registrace", widget: "string", required: false}
      - {label: "Vstupné - není povinné vyplnit", name: "vstupne", widget: "string", required: false}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
    sort:
      by: title
  - name: "krouzky"
    label: "Krouzky"
    folder: "krouzkyMD"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/krouzky.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "krouzkyMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Čas kroužku - není povinné vyplnit", name: "kdy", widget: "string", required: false}
      - {label: "Misto konani akce", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Poplatek - není povinné vyplnit", name: "polatek", widget: "string", required: false}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "aktivity"
    label: "Aktivity"
    folder: "aktivityMD"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/aktivity.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "aktivityMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Čas aktivity", name: "kdy", widget: "string"}
      - {label: "Misto konani aktivity", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Stránky registrace - není povinné vyplnit", name: "registrace", widget: "string", required: false}
      - {label: "Poplatek - není povinné vyplnit", name: "polatek", widget: "string", required: false}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "vylety"
    label: "Vylety"
    folder: "vyletyMD"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/vylety.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "vyletyMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Misto konani vylety", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Foto do fotogalerie - 1", name: "foto1", widget: "image", required: false}
      - {label: "Alternativni text k foto 1", name: "alt1", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 2", name: "foto2", widget: "image", required: false}
      - {label: "Alternativni text k foto 2", name: "alt2", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 3", name: "foto3", widget: "image", required: false}
      - {label: "Alternativni text k foto 3", name: "alt3", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 4", name: "foto4", widget: "image", required: false}
      - {label: "Alternativni text k foto 4", name: "alt4", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 5", name: "foto5", widget: "image", required: false}
      - {label: "Alternativni text k foto 5", name: "alt5", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 6", name: "foto6", widget: "image", required: false}
      - {label: "Alternativni text k foto 6", name: "alt6", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 7", name: "foto7", widget: "image", required: false}
      - {label: "Alternativni text k foto 7", name: "alt7", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 8", name: "foto8", widget: "image", required: false}
      - {label: "Alternativni text k foto 8", name: "alt8", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 9", name: "foto9", widget: "image", required: false}
      - {label: "Alternativni text k foto 9", name: "alt9", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 10", name: "foto10", widget: "image", required: false}
      - {label: "Alternativni text k foto 10", name: "alt10", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 11", name: "foto11", widget: "image", required: false}
      - {label: "Alternativni text k foto 11", name: "alt11", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 12", name: "foto12", widget: "image", required: false}
      - {label: "Alternativni text k foto 12", name: "alt12", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 13", name: "foto13", widget: "image", required: false}
      - {label: "Alternativni text k foto 13", name: "alt13", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 14", name: "foto14", widget: "image", required: false}
      - {label: "Alternativni text k foto 14", name: "alt14", widget: "string", required: false}
      - {label: "Foto do fotogalerie - 15", name: "foto15", widget: "image", required: false}
      - {label: "Alternativni text k foto 15", name: "alt15", widget: "string", required: false}
  - name: "tabory"
    label: "Tabory"
    folder: "taboryMD"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/tabory.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "taboryMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Čas táboru", name: "kdy", widget: "string"}
      - {label: "Misto konani tabory", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Poplatek - není povinné vyplnit", name: "polatek", widget: "string", required: false}
      - {label: "Text", name: "body", widget: "markdown"}