backend:
  name: git-gateway
  branch: main
media_folder: "images/akce"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "akce"
    label: "Akce"
    folder: "akceMD"
    create: true
    slug: "{{SouborRok}}{{SouborMesic}}{{SouborDen}}_{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/akce.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "akceMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum akce odkdy dokdy", name: "kdy", widget: "string"}
      - {label: "Název souboru rok", name: "SouborRok", widget: "string", default: "2023"}
      - {label: "Název souboru měsíc", name: "SouborMesic", widget: "string"}
      - {label: "Název souboru den", name: "SouborDen", widget: "string"}
      - {label: "Misto konani akce", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Vstupné", name: "vstupne", widget: "string"}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "krouzky"
    label: "Krouzky"
    folder: "krouzkyMD"
    create: true
    slug: "{{SouborRok}}{{SouborMesic}}{{SouborDen}}_{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/krouzky.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "krouzkyMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Čas kroužku", name: "kdy", widget: "string"}
      - {label: "Název souboru rok", name: "SouborRok", widget: "string", default: "2023"}
      - {label: "Název souboru měsíc", name: "SouborMesic", widget: "string"}
      - {label: "Název souboru den", name: "SouborDen", widget: "string"}
      - {label: "Misto konani akce", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Poplatek", name: "polatek", widget: "string"}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "aktivity"
    label: "Aktivity"
    folder: "aktivityMD"
    create: true
    slug: "{{SouborRok}}{{SouborMesic}}{{SouborDen}}_{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/aktivity.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "aktivityMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Čas aktivity", name: "kdy", widget: "string"}
      - {label: "Název souboru rok", name: "SouborRok", widget: "string", default: "2023"}
      - {label: "Název souboru měsíc", name: "SouborMesic", widget: "string"}
      - {label: "Název souboru den", name: "SouborDen", widget: "string"}
      - {label: "Misto konani aktivity", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Poplatek", name: "polatek", widget: "string"}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "vylety"
    label: "Vylety"
    folder: "vyletyMD"
    create: true
    slug: "{{SouborRok}}{{SouborMesic}}{{SouborDen}}_{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/vylety.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "vyletyMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Čas výletu", name: "kdy", widget: "string"}
      - {label: "Název souboru rok", name: "SouborRok", widget: "string", default: "2023"}
      - {label: "Název souboru měsíc", name: "SouborMesic", widget: "string"}
      - {label: "Název souboru den", name: "SouborDen", widget: "string"}
      - {label: "Misto konani vylety", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Poplatek", name: "polatek", widget: "string"}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "tabory"
    label: "Tabory"
    folder: "taboryMD"
    create: true
    slug: "{{SouborRok}}{{SouborMesic}}{{SouborDen}}_{{title}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "/partials/tabory.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "taboryMD"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Čas táboru", name: "kdy", widget: "string"}
      - {label: "Název souboru rok", name: "SouborRok", widget: "string", default: "2023"}
      - {label: "Název souboru měsíc", name: "SouborMesic", widget: "string"}
      - {label: "Název souboru den", name: "SouborDen", widget: "string"}
      - {label: "Misto konani tabory", name: "kde", widget: "string"}
      - {label: "Plakat maximální velikost šířka 500px", name: "foto", widget: "image"}
      - {label: "Alternativni text", name: "alt", widget: "string"}
      - {label: "Webove stránky - není povinné vyplnit", name: "web", widget: "string", required: false}
      - {label: "Poplatek", name: "polatek", widget: "string"}
      - {label: "Tagy", name: "myTags", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}